---
title: "things i'm thinking about right now"
date: 2023-04-16T21:51:13-07:00
draft: false

categories: 
- now

---


random shit that has been taking up my neurons and bugging the shit out of me today and making me not get anything done

1. theo von and caleb pressley turkey hunting together and then breaking it down on theo's pod: [turkey hunting](https://youtu.be/Cx-oMeoFJkg) [theo and caleb turkey pod](https://youtu.be/1w_dm1U0ing) shit has no business being that funny
2. this stupid book that is messing with my BRAIN: [cloud atlas by david mitchell](https://en.wikipedia.org/wiki/Cloud_Atlas_(novel)) (review coming soon once i actually finish it)
3. the single chromosome yeast that these people made just to see if it would live and then proceeded to get published in nature: [single chromosome yeast](https://www.nature.com/articles/s41586-018-0382-x#Sec1)
4. drop stop roll by rainbow kitten surprise (i can't figure out what the lyrics mean and i keep listening to it and getting nowhere)
5. my to do list full of tasks (most of which are just sending emails) that continues to grow because i refuse to do any of it
6. the new nytimes game digits: [digits](https://www.nytimes.com/games/digits)