---
title: "2023 books"
draft: false

---


<!-- # 2023 reading lists -->
been looking for some reading projects and have successfully found a couple! will (hopefully) be updating this as i check categories off

#### 52 book club 2023 challenge
*books for this challenge are tagged with 52books23*

**link** -> https://www.the52book.club/2023-reading-challenge/

```mermaid
pie title 52 book club 2023 challenge
    "Finished" : 18
    "Still to read" : 34
```

**1** - book with a subtitle: [Say Nothing: A True Story of Murder and Memory in Northern Ireland]({{< ref "posts/saynothing" >}}) \
**2** - featuring an inheritance: [Reproduction]({{< ref "posts/reproduction" >}}) - at least one that's sought after \
**3** - starts with a G: [The Girl Who Played With Fire]({{< ref "posts/girlplayedwithfire" >}}) \
**4** - starts with an H: [The Healing of America]({{< ref "posts/healingofamerica" >}})  \
**5** - starts with an I: [Isaac and the Egg]({{< ref "posts/isaacandtheegg" >}})  \
**6** - under 200 pages: [By the River Piedra I Sat Down and Wept]({{< ref "posts/riverpiedra" >}})  \
**7** - city or country name in the title: [American Gods]({{< ref "posts/americangods" >}})  \
**8** - dystopian fiction: [Cloud Atlas]({{< ref "posts/cloudatlas" >}}) - one of the storylines is dystopian, so that counts right? \
**11** - book about secrets: [A Thousand Acres]({{< ref "posts/thousandacres" >}}) \
**12** - high fantasy: [A Court of Thorns and Roses]({{< ref "posts/acotar" >}}) \
**14** - a survival story: [Demon Copperhead]({{< ref "posts/demoncopperhead" >}}) \
**18** - set during a war other than WWI or WWII: [Safe Area Goražde]({{< ref "posts/safearea" >}}) \
**20** - book about siblings: [Bridge of Clay]({{< ref "posts/bridgeofclay" >}}) \
**21** - second-hand book: [The Spirit Catches You and You Fall Down]({{< ref "posts/spiritcatchesyou" >}}) - honestly 90% of my books are secondhand so this was an easy one \
**26** - has an epilogue: [Bel Canto]({{< ref "posts/bel_canto" >}}) - it's a garbage one but it's there \
**28** - includes a funeral: [Breathing Lessons]({{< ref "posts/breathinglessons" >}}) \
**29** - sends you down a rabbit hole: [Tomorrow and Tomorrow and Tomorrow]({{< ref "posts/tmrw_cubed" >}}) - maybe i should get into game design \
**35** - a book you meant to read last year: [Cloud Cuckoo Land]({{< ref "posts/cloudcuckoo" >}}) \
