---
title: "2024 books"
draft: false
---


[list of 2024 reading challenges](https://candidcover.net/2024-reading-challenges-list/)


### 52 book club 2024 challenge
*books for this challenge are tagged with #52books24*

<!-- ```goat
.--+--+--+--+--+--+--+--+--+--+--+--+--.
|1 |2 |3 |4 |5 |6 |7 |8 |9 |10|11|12|13|
+--+--+--+--+--+--+--+--+--+--+--+--+--.  
|14|15|16|17|18|19|20|21|22|23|24|25|26|   
+--+--+--+--+--+--+--+--+--+--+--+--+--.    
|27|28|29|30|31|x |33|34|35|36|37|38|39|
+--+--+--+--+--+--+--+--+--+--+--+--+--.
|40|41|42|43|44|45|46|47|48|49|50|51|52|   
'--+--+--+--+--+--+--+--+--+--+--+--+--' 
``` -->




**link** -> https://www.the52book.club/2024-reading-challenge/

**challenge guide link** -> https://www.the52book.club/2024-challenge-guide/

| Prompt                            | Book                                                                      |
|-----------------------------------|---------------------------------------------------------------------------|
| 4. Lowercase letters on the spine | [ Before the coffee gets cold ](books/beforethecoffeegetscold/index.qmd)    |
| 7. At least 4 different POV       | [ Let the Great World Spin ](books/letthegreatworldspin/index.qmd)          |
| 8. Features the ocean       | [ The Perfect Storm ](books/theperfectstorm/index.qmd)                            |
| 9. A character-driven novel       | [ Babel: An Arcane History ](books/babel/index.qmd)                         |
| 10. Told in non-chronological order       | [ Educated ](books/educated/index.qmd)                              |
| 11. Title starting with the letter "K"  | [ Killers of the Flower Moon ](books/killersoftheflowermoon.qmd">}}) |
| 25. An author "everyone" has read except you     | [ Dune Messiah ](books/dunemessiah/index.qmd)                |
| 26. Hybrid genre                  | [ The Complete Maus ](books/maus/index.qmd)                                 |
| 28. A yellow spine                  | [ Somewhere Beyond the Sea ](books/somewherebeyondthesea/index.qmd)       |
| 30. Picked without reading the blurb    | [ The God of Small Things ](books/godofsmallthings.qmd">}})          |
| 36. Has futuristic technology      | [ Foundryside ](books/foundryside/index.qmd)                               |
| 38. Published by Hachette    | [ The Memoirs of Stockholm Sven ](books/thememoirsofstockholmsven.qmd">}})      |
| 41. A sticker on the cover   | [ Tom Lake ](books/tomlake/index.qmd)                                            |
| 43. About finding identity            | [ The Boys in the Boat ](books/boysintheboat.qmd">}})                  |
| 44. Includes a wedding            | [ The Princess Bride ](books/princessbride.qmd">}})                        |
| 45. Chapter headings have dates   | [ The Dictionary of Lost Words ](books/dictionaryoflostwords/index.qmd)     |
| 50. A musical instrument on the cover   | [ King Zeno ](books/kingzeno/index.qmd)                               |



### read the alphabet
*books for this challenge are tagged with #abc24*

A. \
B. [ Before the coffee gets cold ](books/beforethecoffeegetscold/index.qmd) \
C. \
D. [ The Dictionary of Lost Words ](books/dictionaryoflostwords/index.qmd) \
E. [ Educated ](books/educated/index.qmd) \
F. [ Foundryside ](books/foundryside/index.qmd) \
G. [ The God of Small Things ](books/godofsmallthings.qmd">}}) \
H. \
I. \
J. \
K. [ Killers of the Flower Moon ](books/killersoftheflowermoon/index.qmd) \
L. [ Let the Great World Spin ](books/letthegreatworldspin/index.qmd) \
M. [ Midnight in the Garden of Good and Evil ](books/midnightinthegardenofgoodandevil/index.qmd) \
N. \
O. [ Our Hideous Progeny ](books/ourhideousprogeny/index.qmd) \
P. \
Q. \
R. \
S. [ Somewhere Beyond the Sea ](books/somewherebeyondthesea/index.qmd) \
T. [ Tom Lake ](books/tomlake/index.qmd) \
U. [ Unbroken ](books/unbroken/index.qmd) \
V. \
W. [ Watchmen ](books/watchmen/index.qmd) \
X. \
Y. \
Z.


### other challenges i am using for inspiration

[Austine Decker's Beat the Backlist](https://austinedecker.com/beat-the-backlist/)


### last year
[ 2023 reading ](2023reading.qmd)