---
title: "book stats"
format: 
    html:
        code-fold: true

---

## 2025 book stats

total books read: 14



### some silly graphs
```{python}
#| label: genre-stats

import matplotlib.pyplot as plt
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# updated 5-12-25
fiction = 7
nonfiction = 3

## make fic/non-fic pie chart 
genre_labels = ['fiction', 'non-fiction']
genre_num = [fiction, nonfiction]
# genre_colors = ['#56505d', '#df3a26']
genre_colors2 = ['gold', 'mediumturquoise']
d1 = {'genre': genre_labels, 'books': genre_num}
genre_df = pd.DataFrame(data=d1)
# fig = px.pie(genre_df, values='books', names='genre')

## make abcs pie chart
abc_read = 6
abc_unread = 20 
abc_labels = ['read', 'unread']
abc_num = [abc_read, abc_unread]
colors = ['#56505d', '#df3a26']
abc_colors3 = ['darkorange', 'lightgreen']
# fig = px.pie(genre_df, values='books', names='genre')


## make 52books pie chart
fivetwo_read = 6
fivetwo_unread = 46
fivetwo_labels = ['read', 'unread']
fivetwo_num = [fivetwo_read, fivetwo_unread]
colors = ['#56505d', '#df3a26']
fivetwo_colors3 = ['#FE621D', '#DBB1BC']
# fig = px.pie(genre_df, values='books', names='genre')


## make bar chart of books by month
months = ['jan 25', 'feb 25', 'mar 25', 'apr 25', 'may 25']
counts = [1, 2, 1, 5, 1]
d = {'month': months, 'books': counts}
df = pd.DataFrame(data=d)



# fig, (ax1, ax2) = plt.subplots(1, 2)


# ax2 = px.line(df, x="month", y="books", title='books read by month', markers=True)
# fig.show()

fig = make_subplots(
    rows=3, cols=2,
    specs=[[{"type": "pie"}, {"type": "xy", "rowspan": 3}],
           [{"type": "pie"},            None            ],
           [{"type": "pie"},            None           ]],
    print_grid=False,
    subplot_titles=("fiction/non-fiction", "books read per month", "abcs", "52 books challenge"))


# fig = make_subplots(rows=1, cols=2, subplot_titles=("fiction/non-fiction", "books read per month"), specs=[[{"type": "pie"}, {"type": "xy"}]])
fig.add_trace(go.Pie(values = genre_num, labels = genre_labels, name='genres'), row = 1, col = 1)
fig.update_traces(selector=dict(name='genres'), hoverinfo='label+percent', textinfo='value', textfont_size=15,
                  marker=dict(colors=genre_colors2, line=dict(color='#000000', width=2)))

fig.add_trace(go.Pie(values = abc_num, labels = abc_labels, name='abcs'), row = 2, col = 1)
fig.update_traces(selector=dict(name='abcs'), hoverinfo='label+percent', textinfo='value', textfont_size=15,
                  marker=dict(colors=abc_colors3, line=dict(color='#000000', width=2)))

fig.add_trace(go.Pie(values = fivetwo_num, labels = fivetwo_labels, name='fivetwo'), row = 3, col = 1)
fig.update_traces(selector=dict(name='fivetwo'), hoverinfo='label+percent', textinfo='value', textfont_size=15,
                  marker=dict(colors=fivetwo_colors3, line=dict(color='#000000', width=2)))

fig.add_trace(
    go.Scatter(x=months, y=counts),
    row=1, col=2
)
fig.update_layout(height=500, showlegend=False)
fig.show()



```





### abcs 2025
reading the alphabet

| abcs 25 |   |
|---------|---|
|    a    |   |
|    b    |   |
|    c    |   |
|    d    |   |
|    e    |   |
|    f    |   |
|    g    |[ Going Clear ](books/goingclear/index.qmd)   |
|    h    |[ Hidden Figures ](books/hiddenfigures/index.qmd)   |
|    i    |   |
|    j    |   |
|    k    |   |
|    l    |[ Libby Lost and Found ](books/libbylostandfound/index.qmd)   |
|    m    |[ Migrations ](books/migrations/index.qmd)   |
|    n    |[ Nexus ](books/nexus/index.qmd)   |
|    o    |   |
|    p    |   |
|    q    |   |
|    r    |   |
|    s    |[ Shantaram ](books/shantaram/index.qmd)   |
|    t    |   |
|    u    |   |
|    v    |   |
|    w    |   |
|    x    |   |
|    y    |   |
|    z    |   |





### 52 books challenge 2025

| prompt                                    | book |
|-------------------------------------------|------|
| 1. A pun in the title                     |      |
| 2. A character with red hair              |      |
| Title starts with letter “M”              |      |
| Title starts with letter “N”              |      |
| Plot includes a heist                     |      |
| Genre One: Set in Spring                  |      |
| Genre Two: Set in Summer                  |      |
| Genre Three: Set in Autumn                |      |
| Genre Four: Set in Winter                 |      |
| Author’s last name is also a first name   |      |
| A prequel                                 |      |
| Has a moon on the cover                   |      |
| Title is ten letters or less              |      |
| Climate fiction                           |      |
| Includes Latin American history           |      |
| Author has won an Edgar award             |      |
| Told in verse                             |      |
| A character who can fly                   |      |
| Has short chapters                        |      |
| A fairy tale retelling                    |      |
| Character’s name in the title             |      |
| Found family trope                        |      |
| A sprayed edge                            |      |
| Title is a spoiler                        |      |
| Breaks the fourth wall                    |      |
| More than a million copies sold           |      |
| Features a magician                       |      |
| A crossover (Set in a shared universe)    |      |
| Shares universe with prompt 28            |      |
| In the public domain                      |      |
| Audiobook has multiple narrators          |      |
| Includes a diary entry                    |      |
| A standalone novel                        |      |
| Direction in the title                    |      |
| Written in third person                   |      |
| Final sentence is less than 6 words long  |      |
| Genre chosen for you by someone else      |      |
| An adventure story                        |      |
| Has an epigraph                           |      |
| Stream of consciousness narrative         |      |
| Cover font is in a primary color          |      |
| Non-human antagonist                      |      |
| Explores social class                     |      |
| A celebrity on the cover                  |      |
| Author releases more than one book a year |      |
| Read in a “-ber” month                    |      |
| “I think it was blue”                     |      |
| Related to the word “puzzle”              |      |
| Set in a country with an active volcano   |      |
| Set in the 1940s                          |      |
| 300-400 pages long                        |      |
| Published in 2025                         |      |



## all time stats 
check them out here -> [all time stats](alltimebookstats.qmd)

## last year
[ 2024 reading ](2024reading.md)