---
title: "Going Clear: Scientology, Hollywood, and the Prison of Belief / Lawrence Wright "
date: 2025-05-14T23:19:51-04:00
draft: false

categories:
- non-fiction
---
**finished 3/11/25** \
hey, did you guys know that scientology is insane? ron was just on a boat as "commodore" running around because they were in legal trouble in so many countries that they couldn't go into most ports. also, they actually think that L. Ron Hubbard has been in space (in a previous life) and that it's warm up there? in all seriousness, this book is a terrifying look into a cult that wraps you up and never lets you leave. the Rehabilitation Project Force is so scary, and the many stories of people who have attempted to leave the church, only to be stalked and coaxed back in is really upsetting. a scary look at the power of ignorance and the influence of fame and also all of the insane shit they did during operation snow white and just generally all of the insane shit ron and david miscavige have done.

sidenote: crazy scientology website [here](https://tonyortega.org/) 
(article about ron seeing space wars [here](https://tonyortega.org/2021/10/08/scientology-founder-l-ron-hubbards-cosmos-an-ancient-battlefield-shot-through-with-psychs/))