---
title: "Watchmen / Alan Moore, Dave Gibbons"
date: 2024-01-23T18:55:28-05:00
draft: false

categories:
- fiction
- graphic novel
- abc24
---
**finished 1/21/24** \
love a good graphic novel- this one is dark and ominous and made me do a lot of thinking about how the world functions when at war. i really liked the character development, which i think was also influenced by this book being a graphic novel, because you can visually see how the author envisioned the characters, rather than just by description. the art was fantastic as well, because it was also dark and dramatic and matched with the mood of the story. i also liked how the major tragedy at the end did end up happening, and the authors didn't shy away from the pseudo-superheroes not saving the day. at the end of the day, they were just weirdo normal-ish people who just decided to become superheroes based on their elevated egos and anxieties about the state of the world. rorschach was a super interesting character, because his superhero identity  started out well intentioned, but then devolved into this villanous character who acted under the pretense of ridding society of evils, but did a lot of evil himself. really well done.