---
title: "The Story of the Human Body / Daniel E. Lieberman"
date: 2023-12-16T10:10:16-05:00
draft: false

categories:
- non-fiction
- science
---
**finished 12/7/23**

had to think about this one for a minute. i loved all of this book except for the last 3 chapters- the other chapters are super informative and fascinating and full of cool facts about our bodies. i was introduced to so many new ideas (mismatch diseases, dysevolution etc) that were so interesting, and definitely will have me thinking differently about my body when it is sick or injured. that said, the last 3 or so chapters bugged me because he begins to address solutions to some of the problems created by mismatch between our bodies and environments, but most, if not all, of his solutions come from a very privileged position. many of the suggested solutions base themselves on the assumption that all people have access and/or the means to access things such as fresh fruits and veggies, probiotics, jobs that require the 'right' amount of stress or activity etc. the mismatches between our bodies and modern environment affect all people, and so solutions need to cater to people from all walks of life. i don't know the answers either, but the ones in the book definitely aren't for everyone.