---
title: "Shantaram / Gregory David Roberts"
date: 2025-05-14T17:56:38-04:00
draft: false

categories:
- fiction
---
**finished 4/12/25** \
got to love an adventure story. one of those books that makes you really wonder what of it is true in terms of what actually happened, or true in the sense that the story evokes emotions that are truthful to the actual event. definitely glad i stuck with it through the slow parts, because the things that happen at the end are crazy. i looked up my guy gregory and now he's busy posting weird psychedelic edits to his songs on instagram, so go him i guess. seems like prison is at least a great place to write about what got you in there, because this book turned out pretty good. it's about community and personal imperfections and how you can still be a good person even if you have done bad things and continue to do bad things if you are doing them for the right reasons. and also about how to escape from prison. and how to get into illegal passport production. 