---
title: "Our Hideous Progeny / C. E. McGill"
date: 2024-02-26T23:43:38-05:00
draft: false

categories:
- fiction
- abc24
---
**finished 2/24/24** \
this was a really interesting one- i don't think it's one i ever would have picked out for myself, but mama got it for me for christmas and the cover art is wicked cool (but don't judge a book by it's cover) so i gave it a shot. it's inspired by frankenstein and is about a woman and her idiot husband and the woman discovers her great-uncle's research where he made a man come alive. mary and her dummy husband are both geologists and decide to try this on a plesiosaurus because why not and that's the story. but also it's about mary and her miscarriage and being a woman in the mid 19th century and having no autonomy or voice in a conversation and also it's queer and mary has a thing for her stupid husband's sister and it's about grief and letting go of the things you love or once loved. i never watched that movie the way of water but based on the trailers i kind of imagined the Creature like the thing from that movie. i don't know i really liked it because it didn't try too hard to be something it wasn't. 
