---
title: "Dune Messiah / Frank Herbert"
date: 2024-05-05T21:48:13-04:00
draft: false

categories:
- fiction
- 52books24
---
**finished 5/3/24** \
this was tricky to get into because i had forgotten a lot of what happened in Dune, and was getting confused between the movies and the book. also i was confused because it starts after the 12 year jihad, which Paul literally spent all of the first book talking about preventing, and then this book started and was like "ok the jihad happened and billions of people died and Paul is Emperor ok go." but overall i really liked it- i liked that Paul becomes more of a villain and the dynamic of group that is trying to kill him (they all kind of hate each other which was pretty funny even though the dictatorship wins in the end and they are all killed) and the plot was really enticing. was skeptical at first because the jihad was just kind of glossed over within the first couple chapters (it is revisited more in the rest of the book) and it seemed like a big thing to skip, but i can see why it wasn't super relevant to include all the gory details after reading the whole book. good read!