---
title: "My Year of Rest and Relaxation / Ottessa Moshfegh"
date: 2025-05-12T22:50:34-04:00
draft: false

categories:
- fiction
- 52books25
---
**finished 5/10/25** \
ok this was weird. kind of really upsetting to read, especially as a young woman. i really liked the writing style, and how internal monologue-y it was- it felt really authentic to a real person's stream of consciousness, and the narrator felt authentic. i didn't really get it though. it seemed like at the end, her plan of being rich and sleeping for a year just kind of worked? and she was able to like get away with this ridiculousness because she is beautiful and wealthy and has surrounded herself with people who don't hold her accountable? maybe that's the point, that today if you have enough money and social status and manipulative powers, you can kind of do whatever. idk the ending made me feel icky, and i did not like ping xi also and i wanted someone to not be horrible by the end and have a bit of a character arc but they are all not good people and maybe that was the point. kind of funny also

3.5/5